version: "3.5"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: ch-nacos-2
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: on-failure
  mysql:
    container_name: ch-mysql-2
    image: nacos/nacos-mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  prometheus:
    container_name: ch-prometheus-2
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: ch-grafana-2
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure
  redis:
    container_name: ch-redis-2
    image: docker.io/redis:latest
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    restart: on-failure

